version: '3'

services:
  # monitoring linux host metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    ports:
      - 9100:9100

  # monitoring metrics for the running containers
  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    ports:
    - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  # event monitoring and alerting
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - prometheus-data:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - node-exporter:node-exporter
      - cadvisor:cadvisor

  # database for analytics & monitoring solution
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    user: "1000" # grafana needs permisions
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    links:
      - prometheus:prometheus
    depends_on: 
      - prometheus
      
volumes:
  grafana-data:
  prometheus-data:
