global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'server-monitor'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090']
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node-exporter:9100']
  - job_name: 'cAdvisor' 
    static_configs:
     - targets: ['cadvisor:8080']

